server:
  port: 18080
spring:
  application:
    name: spring-ai-alibaba-openmanus
  profiles:
    active: h2
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: qwen3:30b-a3b
    mcp:
      client:
        enabled: false
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  file:
    name: ./logs/info.log
  level:
    root: INFO
