server:
  port: 18080
spring:
  application:
    name: spring-ai-alibaba-openmanus
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: qwen3:30b-a3b
    mcp:
      client:
        enabled: true
  # H2 database configuration
  datasource:
    url: jdbc:h2:file:./h2-data/openmanus_db;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: $FSD#@!@#!#$!12341234
  # JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  # H2 console configuration
  h2:
    console:
      enabled: false
      path: /h2-console
logging:
  file:
    name: ./logs/info.log
  level:
    root: INFO
